"""Add extra_data to customer_segments

Revision ID: b4b707c0d9f8
Revises: 89d63a900646
Create Date: 2025-12-02 16:14:02.846814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4b707c0d9f8'
down_revision: Union[str, None] = '89d63a900646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('behavior_analysis', sa.Column('org_type', sa.Enum('banking', 'telecom', 'ecommerce', name='org_type_enum'), nullable=False))
    op.add_column('behavior_analysis', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('behavior_analysis', 'metadata')
    op.add_column('customer_segments', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('customer_segments', 'metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_segments', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('customer_segments', 'extra_data')
    op.add_column('behavior_analysis', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('behavior_analysis', 'extra_data')
    op.drop_column('behavior_analysis', 'org_type')
    # ### end Alembic commands ###
